### ISSUE TITLE
JIRA lookup failure causes immediate death

### ISSUE THREAD

**Issue by vdanen** [psss/did#134]
If you have multiple JIRA stanzas because you're looking at activity across multiple JIRA products, if there is a problem with the first one it kills did:

```
Traceback (most recent call last):
  File "/usr/bin/did", line 5, in <module>
    pkg_resources.run_script('did==0.9.1', 'did')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/EGG-INFO/scripts/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/cli.py", line 190, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/stats.py", line 134, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/stats.py", line 134, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/plugins/jira.py", line 140, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/plugins/jira.py", line 94, in search
    result = stats.parent.session.open(
  File "/usr/lib/python2.7/site-packages/did-0.9.1-py2.7.egg/did/plugins/jira.py", line 266, in session
    self._session.open(req)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

The problem is I have 30 JIRA projects and I don't know which one(s) are causing the problems because it doesn't tell me.  So the request is two-fold: don't die, catch the error and move on in these cases and secondly, when it dies, please print out the name of the project so we know which one is wrong (i.e. someone renamed a project perhaps).

**Comment by sochotnicky** [comment]
FWIW, perhaps slightly related would be to provide enable something like this:
https://github.com/psss/did/pull/198

With the above people don't have to have multiple JIRA configs for single JIRA instance and the queries are much faster too

**Comment by sandrobonazzola** [comment]
@vdanen I think this should be already fixed, can you try to reproduce?

**Comment by vdanen** [comment]
> [@vdanen](https://github.com/vdanen) I think this should be already fixed, can you try to reproduce?

Sorry I can't, I no longer use did the way that I used to.  If you feel this is already fixed, you can probably close this.

**Comment by sandrobonazzola** [comment]
Thanks, closing.
