### ISSUE TITLE
Traceback in gerrit.py

### ISSUE THREAD

**Issue by tcerna** [psss/did#138]
Traceback in gerrit.py during generation of status report.

```
# did last
...
...
* Work on tests/preupgrade-assistant-el6toel7: 1 commit
    * 8600d29 - Remove invalid test case.
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 190, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 134, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 134, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/gerrit.py", line 199, in fetch
    self.stats = GerritUnit.fetch(self, 'status:abandoned')
  File "/usr/lib/python2.7/site-packages/did/plugins/gerrit.py", line 173, in fetch
    work_list = self.repo.search(query_string)
  File "/usr/lib/python2.7/site-packages/did/plugins/gerrit.py", line 97, in search
    tickets = self.get_query_result(full_url)
  File "/usr/lib/python2.7/site-packages/did/plugins/gerrit.py", line 70, in get_query_result
    'Cannot retrieve list of changes ({0})'.format(res.getcode()))
IOError: Cannot retrieve list of changes (400)
```

**Comment by tcerna** [comment]
Also filled into bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1472591

**Comment by strider** [comment]
@tcerna, I've had the same issue while using this gerrit url in my .did/config file:

[gerrit]
type = gerrit
url = https://review.openstack.org/gerrit/#/
prefix = GR

But when removing `gerrit/#/`, it works:

[gerrit]
type = gerrit
url = https://review.openstack.org/
prefix = GR

**Comment by tosky** [comment]
I can confirm that the proposed configuration changes has been working for me for a long while. Maybe we just need to update the examples.
