### ISSUE TITLE
Bails out with traceback for TDF Bugzilla

### ISSUE THREAD

**Issue by erAck** [psss/did#167]
With the following config section
```
[tdfbz]
type = bugzilla
prefix = tdf
url = https://bugs.documentfoundation.org/xmlrpc.cgi
```
`did --tdfbz` bails out with
```
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 189, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/bugzilla.py", line 559, in fetch
    if bug.commented(self.user)]
  File "/usr/lib/python2.7/site-packages/did/plugins/bugzilla.py", line 246, in commented
    if (comment["author"] == user.email and
KeyError: u'author'
```
On that Bugzilla instance the field name is '**creator**' instead.

**Comment by psss** [comment]
Thanks for reporting this. Let's support both `author` and `creator` then. Should be fixed in master.
