### ISSUE TITLE
bugzilla plugin stopped working

### ISSUE THREAD

**Issue by kraxel** [psss/did#175]
Worked fine for me when I tried it for the first time.
IIRC that was before bugzilla.redhat.com was updated.
Now throws errors at me every time:

kraxel@sirius ~# did
Status report for the week 51 (2018-12-17 to 2018-12-23).

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Gerd Hoffmann <kraxel@redhat.com>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 190, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/bugzilla.py", line 559, in fetch
    if bug.commented(self.user)]
  File "/usr/lib/python2.7/site-packages/did/plugins/bugzilla.py", line 246, in commented
    if (comment["author"] == user.email and
KeyError: u'author'

**Comment by psss** [comment]
This has already been fixed upstream, see #167. You can install the latest version from git or wait for a fresh rpm package which should land in copr and updates-testing later today.
