### ISSUE TITLE
JIRA plugin can't handle numbers in issues titles

### ISSUE THREAD

**Issue by Madeyro** [psss/did#183]
From the traceback I suspect the plugin can not handle numbers in issues titles.
We use tiles in this format: `OAMG-[0-9]+`

```
$ rpm -q did
$ did-0.12-1.fc28.noarch
````

```
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 198, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 143, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 97, in search
    response = stats.parent.session.get(
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 277, in session
    self.auth_url, auth=gssapi_auth, verify=self.ssl_verify)
  File "/home/makopec/.local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/makopec/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/makopec/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/makopec/.local/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/makopec/.local/lib/python2.7/site-packages/requests/adapters.py", line 224, in cert_verify
    if not cert_loc or not os.path.exists(cert_loc):
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found``

```

**Comment by Madeyro** [comment]
It worked before, so there must be problem on my side. Probably with some certificate.
