### ISSUE TITLE
Connection to JIRA: Unicode error

### ISSUE THREAD

**Issue by onosek** [psss/did#184]
Hi,
I can not use _jira_ template. Config and traceback are listed. I am logged in kerberos. `klist` shows hopefully correct tokens.

`````
[jira]
type = jira
prefix = JIRA
project = Compose (tried "COMPOSE" as well)
url = https://projects.engineering.redhat.com/
ssl_verify = true
`````

`````
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 198, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 136, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 79, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 143, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 97, in search
    response = stats.parent.session.get(
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 277, in session
    self.auth_url, auth=gssapi_auth, verify=self.ssl_verify)
  File "/home/onosek/.local/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/onosek/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/onosek/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/onosek/.local/lib/python2.7/site-packages/requests/adapters.py", line 412, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/onosek/.local/lib/python2.7/site-packages/requests/adapters.py", line 225, in cert_verify
    if not cert_loc or not os.path.exists(cert_loc):
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, int found
`````

**Comment by onosek** [comment]
with config option `ssl_verify = false` it works as needed. After reviewing it can be closed.
