### ISSUE TITLE
[bugzilla] xml.parsers.expat.ExpatError: not well-formed (invalid token): line 18, column 0

### ISSUE THREAD

**Issue by hrw** [psss/did#219]
Linaro's bugzilla defined in config:
```
[linaro-bz]
type = bugzilla
prefix = BZL
url = https://bugs.linaro.org/xmlrpc.cgi
resolutions = all
```

Let me run ```did --since 2019-02-01 --until 2019-03-01 --debug --linaro-bz-filed```:

```
 DEBUG  {'bugs': {}, 'comments': {}}
 INFO  Searching for bugs filed by marcin.juszkiewicz@linaro.org
 DEBUG  Search query:
 DEBUG  {'f1': 'reporter',
 'f2': 'creation_ts',
 'f3': 'creation_ts',
 'o1': 'equals',
 'o2': 'greaterthan',
 'o3': 'lessthan',
 'query_format': 'advanced',
 'v1': 'marcin.juszkiewicz@linaro.org',
 'v2': '2019-02-01',
 'v3': '2019-03-02'}
 DEBUG  Search result:
 DEBUG  [<Bug #4293 on https://bugs.linaro.org/xmlrpc.cgi at 0x7f86d1582250>]
 DEBUG  Fetching bug history
 DEBUG  {'bugs': [{'alias': [],
           'history': [{'changes': [{'added': 'NON REPRODUCIBLE',
                                     'field_name': 'resolution',
                                     'removed': ''},
                                    {'added': 'RESOLVED',
                                     'field_name': 'status',
                                     'removed': 'UNCONFIRMED'}],
                        'when': <DateTime '20190225T15:37:40' at 0x7f86d14efd90>,
                        'who': 'marcin.juszkiewicz@linaro.org'}],
           'id': 4293}]}
 DEBUG  Fetching bug comments
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 180, in _request_helper
    return self.parse_response(response)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 152, in parse_response
    parser.feed(response.text.encode('utf-8'))
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 18, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.7/site-packages/did/cli.py", line 220, in main
    user_stats.check()
  File "/usr/lib/python3.7/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.7/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.7/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.7/site-packages/did/plugins/bugzilla.py", line 382, in fetch
    self.stats = self.parent.bugzilla.search(query, options=self.options)
  File "/usr/lib/python3.7/site-packages/did/plugins/bugzilla.py", line 108, in search
    result = self.server._proxy.Bug.comments({'ids': list(bugs.keys())})
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
    self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 202, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 193, in _request_helper
    raise e
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 180, in _request_helper
    return self.parse_response(response)
  File "/usr/lib/python3.7/site-packages/bugzilla/transport.py", line 152, in parse_response
    parser.feed(response.text.encode('utf-8'))
  File "/usr/lib64/python3.7/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
bugzilla.transport.BugzillaError: not well-formed (invalid token): line 18, column 0
```

https://bugs.linaro.org/show_bug.cgi?id=4293 is a bug if fails on.

**Comment by psss** [comment]
It seems the server is not providing a well-formed response. Here's the minimal reproducer:

    import bugzilla

    url = 'https://bugs.linaro.org/xmlrpc.cgi'

    server = bugzilla.Bugzilla(url=url)
    result = server._proxy.Bug.comments({'ids': [4293]})

Attaching data from the server: [weird.xml.gz](https://github.com/psss/did/files/4085951/weird.xml.gz) Would you like to create a bug for Bugzilla?

**Comment by hrw** [comment]
First have to gain access again:

"Your Bugzilla account has been disabled due to issues delivering emails to your address."

**Comment by sandrobonazzola** [comment]
I think this can be closed
