### ISSUE TITLE
Did crashes when generating a report

### ISSUE THREAD

**Issue by AsciiWolf** [psss/did#240]
After upgrading to Fedora 33, did is crashing when generating a weekly report:

```
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.9/site-packages/did/cli.py", line 222, in main
    user_stats.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.9/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.9/site-packages/did/plugins/wiki.py", line 33, in fetch
    for change in self.proxy.getRecentChanges(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1456, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1342, in parse_response
    p.feed(data)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 445, in feed
    self._parser.Parse(data, False)
xml.parsers.expat.ExpatError: mismatched tag: line 39, column 2
```

The crash seems to be caused by a wiki plugin. I have our internal wiki set in did config, when disabling it, did no longer crashes.

**Comment by AsciiWolf** [comment]
Probably related to #239?

**Comment by psss** [comment]
Yes, this seems to be a duplicte of #239. For the internal wiki instance @mrc0mmand has enabled a `RPC2` endpoint which should work with #242.
