### ISSUE TITLE
Traceback while fetching GitHub content

### ISSUE THREAD

**Issue by sandrobonazzola** [psss/did#282]
```console
$ rpm -qv did
did-0.19-3.fc37.noarch
```

While fetching GitHub content I got:

```python
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.11/site-packages/did/cli.py", line 223, in main
    user_stats.check()
  File "/usr/lib/python3.11/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.11/site-packages/did/stats.py", line 157, in check
    stat.check()
  File "/usr/lib/python3.11/site-packages/did/stats.py", line 77, in check
    self.fetch()
  File "/usr/lib/python3.11/site-packages/did/plugins/github.py", line 132, in fetch
    Issue(issue) for issue in self.parent.github.search(query)]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/did/plugins/github.py", line 79, in search
    data = json.loads(response.text)["items"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

**Comment by mikelolasagasti** [comment]
Can you run it with `--debug`?

I think I've been able to reproduce and get a ` DEBUG  GitHub status code: 403`, but would like to confirm.

Do you have a token configured for your github config for did?

**Comment by mikelolasagasti** [comment]
This traceback is already fixed by https://github.com/psss/did/commit/6cf907c5050f4ff331bf947c97a49d9b47963113 but not part of a release.

You should create a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token as otherwise you've 10 requests per minute limit rather than 5000 per hour.

**Comment by sandrobonazzola** [comment]
confirmed fixed
