### ISSUE TITLE
Fedora 39 failure due to Python 3.12 changes

### ISSUE THREAD

**Issue by sandrobonazzola** [psss/did#316]
On Fedora 39 unit tests are failing on:
```python
Traceback (most recent call last):
  File "/usr/bin/did", line 42, in <module>
    did.cli.main()
  File "/usr/lib/python3.12/site-packages/did/cli.py", line 199, in main
    custom_plugins = did.base.Config().plugins
                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/did/base.py", line 102, in __init__
    self.parser.readfp(codecs.open(path, "r", "utf8"))
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

as the already deprecated `readfp` has been dropped in Python 3.12.

**Comment by sandrobonazzola** [comment]
Fixed by #313
