### ISSUE TITLE
--verbose makes git plugin fail on merges

### ISSUE THREAD

**Issue by maxandersen** [psss/did#343]
`did --verbose` where I have git plugin looking at quarkusio/quarkus I get the following with --debug on:

```
DEBUG  27c5fa68943 - Merge pull request #35622 from rolfedh/update-config-yaml-style
Traceback (most recent call last):
  File "/opt/homebrew/bin/did", line 42, in <module>
    did.cli.main()
  File "/opt/homebrew/lib/python3.11/site-packages/did/cli.py", line 238, in main
    user_stats.check()
  File "/opt/homebrew/lib/python3.11/site-packages/did/stats.py", line 158, in check
    stat.check()
  File "/opt/homebrew/lib/python3.11/site-packages/did/stats.py", line 158, in check
    stat.check()
  File "/opt/homebrew/lib/python3.11/site-packages/did/stats.py", line 78, in check
    self.fetch()
  File "/opt/homebrew/lib/python3.11/site-packages/did/plugins/git.py", line 98, in fetch
    self.stats = self.repo.commits(self.user, self.options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/did/plugins/git.py", line 74, in commits
    directory = re.sub("/[^/]+$", "", commit.split("\n")[1])
                                      ~~~~~~~~~~~~~~~~~~^^^
``` 

the code is assuming commit msg has at least one newline which is NOT the case for merge commits. that's just one line and actual touched files are in the tree.

To avoid crash I've done this locally:

```
if(commit.count("\n") < 2):
                        continue
```
just before the failing line.

to avoid the hard fail. not sure if I'm missing some actions because of that.

**Comment by psss** [comment]
Thanks for filing the issue, should be fixed by #350.
