### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by eduardocerqueira** [psss/did#83]
Getting this error when trying to connect to JIRA.

DEBUG  Connecting to https://xxxx.xxxx..xxxx.com/step-auth-gss
Traceback (most recent call last):
  File "/usr/bin/did", line 36, in <module>
    did.cli.main()
  File "/usr/lib/python2.7/site-packages/did/cli.py", line 191, in main
    user_stats.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 135, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 135, in check
    stat.check()
  File "/usr/lib/python2.7/site-packages/did/stats.py", line 80, in check
    self.fetch()
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 137, in fetch
    self.stats = Issue.search(query, stats=self)
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 94, in search
    result = stats.parent.session.open(
  File "/usr/lib/python2.7/site-packages/did/plugins/jira.py", line 265, in session
    self._session.open(self.auth_url)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

**Comment by eduardocerqueira** [comment]
I guess you may ignore this issue, I downloaded the certs and saved to to my  /etc/pki/tls/certs/newca.crt and now it is working fine!

1. sudo wget -O /etc/pki/tls/certs/newca.crt http://xxx.xxx.xxx/newca.crt
2. sudo update-ca-trust
3. did 

or, if you prefer, could create a context to ignore the certificate verification.

**Comment by psss** [comment]
Thanks, documentation also updated with hint how to set cert location:
https://did.readthedocs.io/en/latest/questions/#certificates
